-- Lisää DROP TABLE lauseet tähän tiedostoon

DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Askare CASCADE;
DROP TABLE IF EXISTS AskareLista CASCADE;
DROP TABLE IF EXISTS Askel CASCADE;
DROP TABLE IF EXISTS AskelLista CASCADE;
DROP TABLE IF EXISTS Luokka CASCADE;
DROP TABLE IF EXISTS LuokkaLista CASCADE;